package: das_modul
version: '0.0-alpha'
author: Oliver Kreischer
supportpage: ...
kurzbeschreibung: 'REDAXO Modul'
compile: 1

requires:
    redaxo: '^5.6'
    packages:
        mform: '^5.1.1'
        mblock: '^2.1.0'
    php:
        version: '>=5.6'

